import type { SalesforceOnboardingRecord } from './types';

export const MOCK_SALESFORCE_FIXTURES: Record<string, SalesforceOnboardingRecord> = {
  // 1. Unauthenticated fresh session
  nw_unauthenticated: {
    Id: 'a0B5g000001Fresh001',
    Name: 'PRE-2026-0001',
    Token__c: 'nw_unauthenticated',
    Student_Name__c: 'Kavita Sharma',
    Student_WhatsApp_Number__c: '9876543210',
    Email_PRE__c: 'kavita.sharma@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: false,
    KYC_Submission_Status__c: 'NOT_STARTED',
  },

  // Default demo token (mapped to Rahul Kumar)
  nw_rahul_genius_2026: {
    Id: 'a0B5g000001Rahul001',
    Name: 'PRE-2026-0982',
    Token__c: 'nw_rahul_genius_2026',
    Student_Name__c: 'Rahul Kumar',
    Student_WhatsApp_Number__c: '9876543210',
    PHONE_NUMBER__c: '9876543210',
    Email_PRE__c: 'rahul.kumar@gmail.com',
    Program_PRE__c: 'NxtWave Genius',
    Program_Registered_UID_PRE__c: 'UID-GENIUS-2026-8831',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: false,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Ramesh Kumar',
    Co_Applicant_Phone_Number_PRE__c: '9848012345',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    Co_Applicant_Employment_Type_PRE__c: 'Salaried',
    Co_Applicant_Monthly_Income_Range_PRE__c: '₹50,000 - ₹75,000',
    CIBIL_Score_Range_PRE__c: '750+',
    KYC_Submission_Status__c: 'IN_PROGRESS',
    Northern_Arc_Overall_Stages__c: 'Review In Progress',
  },

  // 2. Auth success, fresh to program view
  nw_auth_success_fresh: {
    Id: 'a0B5g000001Fresh002',
    Name: 'PRE-2026-0002',
    Token__c: 'nw_auth_success_fresh',
    Student_Name__c: 'Amit Patel',
    Student_WhatsApp_Number__c: '9812345678',
    Email_PRE__c: 'amit.patel@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    KYC_Submission_Status__c: 'NOT_STARTED',
  },

  // 3. Direct pay pending
  nw_direct_pay_pending: {
    Id: 'a0B5g000001Direct001',
    Name: 'PRE-2026-0003',
    Token__c: 'nw_direct_pay_pending',
    Student_Name__c: 'Siddharth Rao',
    Student_WhatsApp_Number__c: '9899887766',
    Email_PRE__c: 'siddharth.rao@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'Full Payment',
    Payment_Status__c: 'Pending',
    Payment_Done_PRE__c: false,
  },

  // 4. Direct pay success
  nw_direct_pay_success: {
    Id: 'a0B5g000001Direct002',
    Name: 'PRE-2026-0004',
    Token__c: 'nw_direct_pay_success',
    Student_Name__c: 'Sneha Reddy',
    Student_WhatsApp_Number__c: '9765432100',
    Email_PRE__c: 'sneha.reddy@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 112000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'Full Payment',
    Payment_Status__c: 'Success',
    Payment_Done_PRE__c: true,
    Receipt_Id__c: 'RCP-DIRECT-2026-0921',
    Payment_Date_Time__c: '2026-09-04T14:30:00Z',
    LMS_Access_Status__c: 'Active',
  },

  // 5. EMI started, no co-applicant yet
  nw_emi_started_no_coapplicant: {
    Id: 'a0B5g000001Emi001',
    Name: 'PRE-2026-0005',
    Token__c: 'nw_emi_started_no_coapplicant',
    Student_Name__c: 'Vikas Verma',
    Student_WhatsApp_Number__c: '9845012345',
    Email_PRE__c: 'vikas.verma@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    KYC_Submission_Status__c: 'NOT_STARTED',
  },

  // 6. EMI co-applicant saved, KYC pending
  nw_emi_coapplicant_saved: {
    Id: 'a0B5g000001Emi002',
    Name: 'PRE-2026-0006',
    Token__c: 'nw_emi_coapplicant_saved',
    Student_Name__c: 'Pooja Iyer',
    Student_WhatsApp_Number__c: '9820011223',
    Email_PRE__c: 'pooja.iyer@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Sundaram Iyer',
    Co_Applicant_Phone_Number_PRE__c: '9820099887',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    Co_Applicant_Employment_Type_PRE__c: 'Salaried',
    Co_Applicant_Monthly_Income_Range_PRE__c: '₹50,000 - ₹75,000',
    CIBIL_Score_Range_PRE__c: '750+',
    KYC_Submission_Status__c: 'NOT_STARTED',
  },

  // 7. EMI KYC in progress
  nw_emi_kyc_in_progress: {
    Id: 'a0B5g000001Emi003',
    Name: 'PRE-2026-0007',
    Token__c: 'nw_emi_kyc_in_progress',
    Student_Name__c: 'Arjun Das',
    Student_WhatsApp_Number__c: '9711223344',
    Email_PRE__c: 'arjun.das@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Fibe',
    Co_Applicant_Name__c: 'Bikash Das',
    Co_Applicant_Phone_Number_PRE__c: '9711998877',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    KYC_Submission_Status__c: 'IN_PROGRESS',
  },

  // 8. EMI KYC action required (blur document / statement missing)
  nw_emi_kyc_action_required: {
    Id: 'a0B5g000001Emi004',
    Name: 'PRE-2026-0008',
    Token__c: 'nw_emi_kyc_action_required',
    Student_Name__c: 'Meera Nair',
    Student_WhatsApp_Number__c: '9655443322',
    Email_PRE__c: 'meera.nair@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Gopal Nair',
    Co_Applicant_Phone_Number_PRE__c: '9655112233',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    KYC_Submission_Status__c: 'ACTION_REQUIRED',
    ADDITIONAL_DETAILS_REQUIRED_PRE_PRE__c:
      'Bank statement photo was blurry. Please re-upload latest 3 months official e-statement PDF.',
    Documents_Requested_By_Reps__c: '3-Month Bank Statement PDF, Clear PAN Card Photo',
  },

  // 9. EMI NBFC under review
  nw_emi_nbfc_under_review: {
    Id: 'a0B5g000001Emi005',
    Name: 'PRE-2026-0009',
    Token__c: 'nw_emi_nbfc_under_review',
    Student_Name__c: 'Gautam Singhania',
    Student_WhatsApp_Number__c: '9870011223',
    Email_PRE__c: 'gautam.s@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Mahesh Singhania',
    Co_Applicant_Phone_Number_PRE__c: '9870099887',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    KYC_Submission_Status__c: 'VERIFIED',
    Northern_Arc_Overall_Stages__c: 'Review In Progress',
    Applied_Loan_Amount__c: 112000,
  },

  // 10. EMI NBFC approved, EMI setup pending
  nw_emi_nbfc_approved: {
    Id: 'a0B5g000001Emi006',
    Name: 'PRE-2026-0010',
    Token__c: 'nw_emi_nbfc_approved',
    Student_Name__c: 'Deepak Joshi',
    Student_WhatsApp_Number__c: '9811223399',
    Email_PRE__c: 'deepak.joshi@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Harish Joshi',
    Co_Applicant_Phone_Number_PRE__c: '9811998811',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    KYC_Submission_Status__c: 'VERIFIED',
    Northern_Arc_Overall_Stages__c: 'EMI Setup Pending',
    Applied_Loan_Amount__c: 112000,
    Effective_Approved_Amount__c: 112000,
  },

  // 11. EMI NBFC rejected (low CIBIL -> change co-applicant)
  nw_emi_nbfc_rejected: {
    Id: 'a0B5g000001Emi007',
    Name: 'PRE-2026-0011',
    Token__c: 'nw_emi_nbfc_rejected',
    Student_Name__c: 'Karthik Menon',
    Student_WhatsApp_Number__c: '9447012345',
    Email_PRE__c: 'karthik.menon@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Prabhakar Menon',
    Co_Applicant_Phone_Number_PRE__c: '9447998877',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    KYC_Submission_Status__c: 'VERIFIED',
    Northern_Arc_Overall_Stages__c: 'Loan Rejected',
    Northern_Arc_Rejected_Reasons__c:
      'Co-Applicant credit bureau score below minimum threshold. Please nominate an alternate co-applicant.',
  },

  // 12. EMI Disbursed, class access pending
  nw_emi_disbursed: {
    Id: 'a0B5g000001Emi008',
    Name: 'PRE-2026-0012',
    Token__c: 'nw_emi_disbursed',
    Student_Name__c: 'Ananya Gupta',
    Student_WhatsApp_Number__c: '9833012345',
    Email_PRE__c: 'ananya.gupta@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 18000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'No-Cost EMI',
    Choose_NBFC_PRE__c: 'Northern Arc',
    Co_Applicant_Name__c: 'Sunil Gupta',
    Co_Applicant_Phone_Number_PRE__c: '9833998877',
    Relation_With_The_Co_Applicant_PRE__c: 'Father',
    KYC_Submission_Status__c: 'VERIFIED',
    Northern_Arc_Overall_Stages__c: 'Loan Disbursed',
    Disbursed_Amount_PRE__c: 112000,
    Disbursed_Date_Time__c: '2026-09-05T10:00:00Z',
    LMS_Access_Status__c: 'Pending',
  },

  // 13. Class Access Active (Final completed state)
  nw_class_access_active: {
    Id: 'a0B5g000001Active01',
    Name: 'PRE-2026-0013',
    Token__c: 'nw_class_access_active',
    Student_Name__c: 'Rohan Deshmukh',
    Student_WhatsApp_Number__c: '9822012345',
    Email_PRE__c: 'rohan.deshmukh@example.com',
    Program_PRE__c: 'NxtWave Genius',
    Product_Price__c: 160000,
    Scholarship_Amount__c: 30000,
    Seat_Reservation_Amount_Paid__c: 18000,
    Amount_Payable_PRE__c: 112000,
    Amount_Paid_Till_Now_To_Nxtwave_PRE__c: 112000,
    Authentication_Verified__c: true,
    Payment_Plan_PRE__c: 'Full Payment',
    Payment_Status__c: 'Success',
    Payment_Done_PRE__c: true,
    Receipt_Id__c: 'RCP-LMS-2026-0182',
    LMS_Access_Status__c: 'Active',
    Batch_Start_Date__c: '15 September 2026',
  },
};
